# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='student',
            new_name='lecturer',
        ),
    ]
